# Generated by Django 3.1.7 on 2021-04-16 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavalStormUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='', null=True, upload_to='avatars/')),
                ('winNumber', models.IntegerField(default=0, verbose_name='winNumber')),
                ('playedGameNumber', models.IntegerField(default=0, verbose_name='playedGameNumber')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navalstormUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
    ]