# Generated by Django 3.1.7 on 2021-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210408_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
