# Generated by Django 3.1.7 on 2021-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210408_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
