# Generated by Django 3.1.7 on 2021-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210415_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='gamer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
