# Generated by Django 3.2 on 2021-04-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('first_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='First_player', to='user.navalstormuser')),
                ('second_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Second_player', to='user.navalstormuser')),
            ],
        ),
    ]
