# Generated by Django 3.1.7 on 2021-04-19 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='first_board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='First_Board', to='game.board'),
        ),
        migrations.AddField(
            model_name='servers',
            name='second_board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Second_Board', to='game.board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servers',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
