# Generated by Django 3.1.7 on 2021-04-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('game', '0002_auto_20210418_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.navalstormuser'),
        ),
    ]
